version: '3'
services:
  vault:
    image: hashicorp/vault:1.13.3
    container_name: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_ADDR: "http://0.0.0.0:8300"
    volumes:
      - ./vault/config:/vault/config
    cap_add:
      - IPC_LOCK
    ports:
      - "8300:8300"
