apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: hashicorp/vault:1.13.3
        ports:
        - containerPort: 8300
        volumeMounts:
        - name: vault-config
          mountPath: /vault/config
        env:
        - name: VAULT_ADDR
          value: "http://0.0.0.0:8300"
      volumes:
      - name: vault-config
        configMap:
          name: vault-config
