apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
data:
  config.hcl: |
    storage "file" {
      path = "/vault/file"
    }
    listener "tcp" {
      address = "0.0.0.0:8300"
      tls_disable = 1
    }
    ui = true
